apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
  creationTimestamp: "2020-09-13T02:17:04Z"
  generation: 27
  labels:
    app: z19rpw
  name: z19rpw
  namespace: default
  resourceVersion: "1301619"
  selfLink: /apis/apps/v1/namespaces/default/deployments/z19rpw
  uid: 1e7b202c-c125-485f-ba70-5b287a89ecb2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: z19rpw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: z19rpw
    spec:
      containers:
      - env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: gcr.io/z19r-com/z19rpw:1.2.15
        imagePullPolicy: IfNotPresent
        name: z19rpw
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=z19r-com:us-central1:zrk19pw=tcp:5432
        - -credential_file=/secrets/service_account.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        imagePullPolicy: IfNotPresent
        name: cloud-sql-proxy
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/
          name: s3kretz
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: s3kretz
        secret:
          defaultMode: 420
          secretName: z19rpw-dbc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-13T04:13:19Z"
    lastUpdateTime: "2020-09-14T04:30:28Z"
    message: ReplicaSet "z19rpw-599c7fd68c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-16T22:42:11Z"
    lastUpdateTime: "2020-09-16T22:42:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
