name: "derploy :allthethings:"

on:
  push:
    branches:
      - "main"

jobs:
  build-and-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: git the code
        uses: actions/checkout@v1
      - name: authmeup
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: mixelixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.1"
          otp-version: "23"
      - name: elixirdeps
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile
      # - name: RUN THE JEWELS
      #   run: mix test
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: bigassets
        run: |
          npm --prefix ./assets ci --progress=false --no-audit --loglevel=error
          npm run --prefix ./assets deploy
      - name: arm64 for build
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build and pu5h
        run: |
          docker buildx build \
          --platform=linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag $(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')/z19rpw:latest
      - name: derploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deployment z19rpw
