name: "[builder] CI for releases"

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub Authentication
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Install Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.1"
          otp-version: "23"
      - name: Elixir Deps
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build Assets
        run: |
          npm --prefix ./assets ci --progress=false --no-audit --loglevel=error
          npm run --prefix ./assets deploy
      - name: Build for arm64
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform=linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag $(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')/z19rpw:latest
