name: "does it blend?"

on: [push, pull_request]

jobs:
  compile-on-three:
    runs-on: ubuntu-latest
    container: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: git the code
        uses: actions/checkout@v1
      - name: mixelixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11."
          otp-version: "23"
      - name: burnbabyburn
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile
          mix test
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
