name: "does it blend?"

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches: "*"

jobs:
  compile-on-three:
    runs-on: ubuntu-latest
    container: elixir:1.11.2-alpine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached

    steps:
      - name: git the code
        uses: actions/checkout@v1
      - name: burnbabyburn
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile
          mix coveralls.github
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          MEMCACHED_HOST: memcached
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
